version: "3"

services:

  nginx:
    image: consomalin/nginx-ldap
    networks: [big]
    volumes:
      - ./nginx2/conf:/app/conf/:ro
    ports:
      - "9000:80"

  theremine:
    build: ./theremine
    networks: [big]
    environment:
      - METRONOME_HOST=http://metronome-cache
    ports:
      - "8080:80"

  kiva:
    build: 
      context: ./haskell
      dockerfile: ./kiva/Dockerfile
    networks: [big]
    ports:
      - "8081:80"

  wendy:
    build:
      context: ./haskell
      dockerfile: ./wendy/Dockerfile
    environment:
      - DRIVE_USER=goto.devnull@mailoo.org
      - DRIVE_PASS=TTOjKLoXg1!
    networks: [big]

  metronome-cache:
    image: consomalin/nginx-ldap
    networks: [big]
    volumes:
      - ./nginx/conf:/app/conf/:ro
      - ./nginx/cache:/app/cache/

  metronome:
    build:
      context: ./haskell
      dockerfile: ./metronome/Dockerfile
    environment:
      - DRIVE_USER=bitcoin.miner@mailoo.org
      - DRIVE_PASS=hDDqSUGmY3!
    networks: [big]
    ports:
      - "8082:80"

  mongo-express:
    image: mongo-express
    networks: [big]
    ports:
      - "8083:8081"

  mongo:
    image: mongo
    networks: [big]
    volumes:
      - ./state/mongo:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.5.5-management
    networks: [big]
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  big:
