extends: airbnb-base
installedESLint: true
plugins:
  - import
rules:
  no-param-reassign: 'off'
  prefer-template: 'off'
  no-plusplus: 'off'
  no-unused-vars: 'warn'
  no-console: 'off'
  no-underscore-dangle: 'off'
  guard-for-in: 'off'
  no-restricted-syntax: 'off'
