version: "3"

networks:
  big:
    driver: overlay

services:

  theremine:
    image: registry.consomalin.ovh:5000/theremine:${commit}
    env_file: env/theremine.env
    networks: [big]

  janitor:
    image: registry.consomalin.ovh:5000/janitor:${commit}
    env_file: env/janitor.env
    networks: [big]

  recorder:
    image: registry.consomalin.ovh:5000/recorder:${commit}
    env_file: env/recorder.env
    networks: [big]

  kiva:
    image: registry.consomalin.ovh:5000/kiva:${commit}
    networks: [big]

  wendy:
    image: registry.consomalin.ovh:5000/wendy:${commit}
    env_file: env/wendy.env
    networks: [big]

  byte-diver:
    image: registry.consomalin.ovh:5000/byte-diver:${commit}
    networks: [big]
    command: sleep infinity

  metronome:
    image: registry.consomalin.ovh:5000/metronome:${commit}
    env_file: env/metronome.env
    networks: [big]
    command: ./metronome
